# sonar.projectKey Adicionado no CI.
sonar.organization=fga-eps-mds-1

sonar.testExecutionReportPaths=./coverage.xml
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.host.url=https://sonarcloud.io

sonar.sources=./src

sonar.language=ts

# TS Metrics
sonar.typescript.tsconfigPath=./tsconfig.json

sonar.tests=./src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/tests/**
sonar.exclusions= **/*.spec.ts, **/*.spec.tsx,**/tests/**, **/_app*.tsx,**/_document*.tsx, **/*.d.ts, **/index.ts, **/index.page.ts, **/styles.ts, **/Theme/**, **/dashboards/**/*.tsx

#----- Default source code encoding
sonar.sourceEncoding=UTF-8

sonar.typescript.tslint.reportPaths=./dist/tslint.json

sonar.coverage.exclusions=src/**/*.d.ts, src/**/styles.ts, src/**/index.ts, src/**/index.tsx, src/**/*.page.ts, src/**/*.page.tsx, /src/shared/services/subCharacteristics.ts, src/**/dashboards/**/*.tsx, src/**/components/ProductContent/**, src/mocks/**
