name: Export de métricas

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install --only-binary :all: -r requirements.txt

      - name: Criar diretório
        run: mkdir analytics-raw-data

      - name: Coletar métricas no SonarCloud
        run: python parser.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Envia métricas para repo de Doc
        env:
          API_TOKEN_DOC: ${{ secrets.API_TOKEN_DOC }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
          git clone --single-branch --branch main "https://x-access-token:${API_TOKEN_DOC}@github.com/fga-eps-mds/2026.2-MeasureSoftGram-DOC" doc
          mkdir -p doc/Analytics/data
          cp -R analytics-raw-data/*.json doc/Analytics/data
          cd doc/
          git add .
          git commit -m "Adicionando métricas do repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push

      - name: Envia métricas como assets da release
        if: startsWith(github.ref, 'refs/tags')
        uses: AButler/upload-release-assets@ec6d3263266dc57eb6645b5f75e827987f7c217d # v2.0
        with:
          files: 'analytics-raw-data/*'
          repo-token: ${{ secrets.TOKEN_GITHUB }}
          release-tag: ${{ github.ref_name }}
