name: Rodar Testes

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar pnpm packages
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Instalar dependência libssl1.1 para o SWC do Next.js
        run: |
          curl --proto '=https' --tlsv1.2 -sSOL https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb || curl --proto '=https' --tlsv1.2 -sSOL https://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Rodar testes
        run: pnpm run ci:test --coverage

      - name: Scanner do SonarCloud
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}

      # - name: Envia cobertura para o Codecov
      #   uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./
      #     fail_ci_if_error: true
      #     files: ./coverage/clover.xml
      #     flags: unittests
      #     name: 2026.2-MeasureSoftGram-Front
      #     verbose: true
